name: Deploy SRB2Kart Web

on:
  push:
    branches:
      - master

permissions:
      contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Game Assets
        run: ./get-assets.sh

      - name: Build Project
        run: yarn build

      - name: Track Large Assets for Deployment
        run: |
          cd launcher-dist
          git init
          git lfs install
          git lfs track "*.kart"
          git lfs track "*.srb"
          git lfs track "*.wad"
          git add .gitattributes
          git add .
        shell: bash

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: launcher-dist
          branch: gh-pages
          lfs: true